name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp-biawa.alwaysdata.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/
          protocol: ftps
          security: loose
          port: 21
          log-level: verbose
          state-name: ".ftp-deploy-sync-state.json"  # Garde un état pour ne pas re-téléverser tout
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**  # Évite de recharger Composer
            **/tests/**
          dangerous-clean-slate: false  # Empêche une suppression massive si un problème survient
